spring:
  cloud:
    inetutils:
      preferredNetworks:
        - 192.168

  kafka:
    consumer:
      bootstrap-servers: localhost:9092  # ak-node1.eprocurement.systems:9092,ak-node2.eprocurement.systems:9092,ak-node3.eprocurement.systems:9092
      group-id: notification-kafka-consumer-group
      enable-auto-commit: false
    producer:
      bootstrap-servers: localhost:9092  # feed.eprocurement.systems:9092
      retries: 5
      security:
        username:
        password:
    listener:
      ack-mode: manual_immediate

cassandra:
  contact-points: localhost  # ac-node1.eprocurement.systems,ac-node2.eprocurement.systems,ac-node3.eprocurement.systems
  keyspace-name: ocds
  port: 9042
  username:
  password:

health:
  config:
    enabled: false

management:
  actuator-security:
    username: actuator
    password-hash: "{bcrypt}$2a$10$MSaYg2SejDhqgxY6DcomQeYwQRxrFXJHgdH.UOkDqBDNzHNIUSQr."

  health:
    #    diskspace:
    #      enabled: true

    db:
      enabled: true
    #    refresh:
    #      enabled: false

    defaults:
      enabled: false

  endpoint:
    health:
      show-details: always
  #    loggers:
  #      enabled: true

  endpoints:
    web:
      exposure:
        include: "health,prometheus"

#    jmx:
#      domain: com.procurement
#      exposure:
#        exclude: "*"
#  metrics:
#    distribution:
#      percentiles-histogram:
#        http:
#          server:
#            requests: true
#      sla:
#        http:
#          server:
#            requests: 1ms,5ms
#     export:
#       jvm:
#         enabled: true
#     enable:
#       jvm: true
#  server:
#    port: 9999
#  info:
#    git:
#      mode: full