spring:
  cloud:
    inetutils:
      preferredNetworks:
        - 192.168

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: notification-kafka-consumer-group-1
      enable-auto-commit: false
    producer:
      bootstrap-servers: localhost:9092
      retries: 5
      security:
        username:
        password:
    listener:
      ack-mode: manual_immediate

cassandra:
  contact-points: localhost
  keyspace-name: ocds
  port: 9042

health:
  config:
    enabled: false

management:
  actuator-security:
    username:
    password-hash: "{bcrypt}"

  health:
    #    diskspace:
    #      enabled: true

    db:
      enabled: true
    #    refresh:
    #      enabled: false

    defaults:
      enabled: false

  endpoint:
    health:
      show-details: always
  #    loggers:
  #      enabled: true

  endpoints:
    web:
      exposure:
        include: "health,prometheus"

#    jmx:
#      domain: com.procurement
#      exposure:
#        exclude: "*"
#  metrics:
#    distribution:
#      percentiles-histogram:
#        http:
#          server:
#            requests: true
#      sla:
#        http:
#          server:
#            requests: 1ms,5ms
#     export:
#       jvm:
#         enabled: true
#     enable:
#       jvm: true
#  server:
#    port: 9999
#  info:
#    git:
#      mode: full
